-- MIGRATION UP VERSI 2

USE Perpustakaan;

CREATE TABLE [BOOK_COPIES](
	[BookId] INT NOT NULL,
	[BranchId] INT NOT NULL,
	[No_Of_Copies] INT
);

CREATE TABLE [BOOK_LOANS](
	[BookId] INT NOT NULL,
	[BranchId] INT NOT NULL,
	[CardNo] INT NOT NULL,
	[DateOut] DATE,
	[DueDate] DATE
);

CREATE TABLE [LIBRARY_BRANCH](
	[BranchId] INT NOT NULL,
	[BranchName] NVARCHAR(64),
	[Address] NTEXT,
	CONSTRAINT [PK_LIBRARYBRANCH] PRIMARY KEY ([BranchId])
);

CREATE TABLE [BORROWER](
	[CardNo] INT NOT NULL,
	[Name] NVARCHAR(64),
	[Address] NTEXT,
	[Phone] NVARCHAR(16),
	CONSTRAINT [PK_BORROWER] PRIMARY KEY ([CardNo])
);

ALTER TABLE [BOOK_LOANS] ADD CONSTRAINT [FK_BOOKLOANS_CardNo] FOREIGN KEY ([CardNo]) REFERENCES [BORROWER] ([CardNo]);
ALTER TABLE [BOOK_LOANS] ADD CONSTRAINT [FK_BOOKLOANS_BranchId] FOREIGN KEY ([BranchId]) REFERENCES [LIBRARY_BRANCH] ([BranchId]);
ALTER TABLE [BOOK_LOANS] ADD CONSTRAINT [FK_BOOKLOANS_BookId] FOREIGN KEY ([BookId]) REFERENCES [BOOK] ([BookId]);
ALTER TABLE [BOOK_COPIES] ADD CONSTRAINT [FK_BOOKCOPIES_BranchId] FOREIGN KEY ([BranchId]) REFERENCES [LIBRARY_BRANCH] ([BranchId]);
ALTER TABLE [BOOK_COPIES] ADD CONSTRAINT [FK_BOOKCOPIES_BookId] FOREIGN KEY ([BookId]) REFERENCES [BOOK] ([BookId]);