-- MIGRATION UP VERSI 1;

USE Perpustakaan;

CREATE TABLE [BOOK](
	[BookId] INT NOT NULL,
	[Title] NVARCHAR(64),
	[PublisherName] NVARCHAR(64),
	CONSTRAINT [PK_BOOK] PRIMARY KEY ([BookId])
);

CREATE TABLE [PUBLISHER](
	[Name] NVARCHAR(64),
	[Address] NTEXT,
	[Phone] NVARCHAR (16),
	CONSTRAINT [PK_PUBLISHER] PRIMARY KEY ([Name])
);

CREATE TABLE [BOOK_AUTHORS](
	[BookId] INT NOT NULL,
	[AuthorName] NVARCHAR (64) NOT NULL,
	CONSTRAINT [PK_BOOKAUTHORS] PRIMARY KEY ([AuthorName]),
	CONSTRAINT [FK_BOOKAUTHORS_BookId] FOREIGN KEY ([BookId]) REFERENCES [BOOK] ([BookId])
);

ALTER TABLE [BOOK] ADD CONSTRAINT [FK_BOOK_PublisherName] FOREIGN KEY ([PublisherName]) REFERENCES [PUBLISHER] ([Name]);