-- MIGRATION UP VERSI 3

USE Perpustakaan;

ALTER TABLE [PUBLISHER] ADD [PublisherId] INT NOT NULL;
ALTER TABLE [BOOK] DROP CONSTRAINT [FK_BOOK_PublisherName];
ALTER TABLE [BOOK] DROP COLUMN [PublisherName];
ALTER TABLE [PUBLISHER] DROP CONSTRAINT [PK_PUBLISHER];
ALTER TABLE [PUBLISHER] ADD CONSTRAINT [PK_PUBLISHER] PRIMARY KEY ([PublisherId]);
ALTER TABLE [BOOK] ADD [PublisherId] INT;
ALTER TABLE [BOOK] ADD CONSTRAINT [FK_BOOK_PublisherId] FOREIGN KEY ([PublisherId]) REFERENCES [PUBLISHER] ([PublisherId]);